### ISSUE TITLE
Add support for listening to all events and wildcards in events

### ISSUE THREAD

**Issue by watzon** [hugoabonizio/event_emitter.cr#6]
Being able to have a catchall would be great for logging purposes and when you don't necessarily know the names of the events. I propose a `.all` method which would do exactly that.

```crystal
emitter = EventEmitter::Base.new

emitter.all do |event, _|
    puts event
end

emitter.emit("testEvent", "Hello world")

# => "testEvent"
```

Allowing wildcards in `.on` would also be nice, or we could allow Regex which would be a bit more powerful. That way we could do:

```crystal
emitter.on(/foo\..*/) { ... }
```

**Comment by hugoabonizio** [comment]
I liked the idea of adding wildcards, just like Redis subscribing with `PSUBSCRIBE`. This may be implemented by converting strings with `*` to Regex expressions. But this might end being a bit more difficult to implement than simple Regex.

**Comment by watzon** [comment]
Yeah I started working on it yesterday, but rolled back the changes because I couldn't get it working right. Turns out with the way things are being done right now it's going to be fairly difficult. I'll keep trying though because this is a feature I'd really like to see.

**Comment by hugoabonizio** [comment]
I have a draft implementation in mind, by changing the `if @channels.has_key? event` condition to look for matching patterns on the current events, and then rematching on each `#on` call, but there may be a more efficient way to the this.

Anyway, I was expecting this to have some caveats :grin:
